### ISSUE TITLE
Automation issues and questions

### ISSUE THREAD

**Issue by tdd** [reactjs/fr.react.dev#452]
@gaearon Hey Dan! How's it been?

Finally kicking the FR re-translation effort into gear 🎉, yay!

We're getting weird GitHub Actions job failures due to oooold Node versions in there. Anything the docs team can fix? Also, any idea when can we expect weekly automated backport/sync PRs from upstream, as we had on the former docs?

Best,

**Comment by gaearon** [comment]
Old Node versions in Actions seem benign, but I filed https://github.com/reactjs/react.dev/issues/5961 to get those updated. When we fix this upstream, you'll get the fix.

I'm not actually sure "Analyze Bundle" makes sense for translations. Since you're not changing the code. But maybe it's less hassle to keep the setup the same.

>Also, any idea when can we expect weekly automated backport/sync PRs from upstream, as we had on the former docs?

Did it break for this repo specifically? I believe the sync bot is sending PRs to other repos. So I'd expect it to "just work".

**Comment by tdd** [comment]
Hey! I didn't see any recent sync PR on the repo, perhaps because we hadn't started any work so no conflict emerged and it just auto-merged or something?

Will keep an eye on this! Closing for now.

**Comment by gaearon** [comment]
Hm yeah I don't see any recent ones. Not sure why. Maybe something broke. If you don't see them coming, let me know and I'll take a closer look.
